# Generated by Django 4.2.28 on 2026-03-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=32)),
                ("account_id", models.CharField(max_length=128)),
                ("project_name", models.CharField(max_length=128)),
                ("auth_ref", models.CharField(max_length=255)),
                ("status", models.CharField(default="active", max_length=32)),
            ],
            options={
                "db_table": "cloud_account",
                "unique_together": {("provider", "account_id", "project_name")},
            },
        ),
        migrations.CreateModel(
            name="CloudInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instance_id", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("region", models.CharField(max_length=64)),
                ("zone", models.CharField(blank=True, max_length=64)),
                ("instance_type", models.CharField(max_length=64)),
                ("image_id", models.CharField(blank=True, max_length=128)),
                ("os_type", models.CharField(blank=True, max_length=64)),
                ("private_ip", models.CharField(blank=True, max_length=64)),
                ("public_ip", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(max_length=32)),
                (
                    "charge_type",
                    models.CharField(
                        choices=[("postpaid", "按量"), ("prepaid", "包年包月")],
                        default="postpaid",
                        max_length=32,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=64)),
                ("env", models.CharField(default="dev", max_length=16)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="assets.cloudaccount",
                    ),
                ),
            ],
            options={
                "db_table": "cloud_instance",
            },
        ),
        migrations.CreateModel(
            name="CloudNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vpc_id", models.CharField(max_length=128)),
                ("subnet_id", models.CharField(max_length=128)),
                ("security_group_id", models.CharField(max_length=128)),
                ("cidr", models.CharField(max_length=64)),
                ("inbound_rules", models.JSONField(default=list)),
                ("outbound_rules", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networks",
                        to="assets.cloudinstance",
                    ),
                ),
            ],
            options={
                "db_table": "cloud_network",
            },
        ),
        migrations.CreateModel(
            name="CloudDisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("disk_id", models.CharField(max_length=128, unique=True)),
                ("disk_type", models.CharField(max_length=64)),
                ("size_gb", models.PositiveIntegerField()),
                ("encrypted", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=32)),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disks",
                        to="assets.cloudinstance",
                    ),
                ),
            ],
            options={
                "db_table": "cloud_disk",
            },
        ),
        migrations.CreateModel(
            name="CloudTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_key", models.CharField(max_length=64)),
                ("tag_value", models.CharField(max_length=255)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="assets.cloudinstance",
                    ),
                ),
            ],
            options={
                "db_table": "cloud_tag",
                "unique_together": {("instance", "tag_key")},
            },
        ),
        migrations.AddIndex(
            model_name="cloudinstance",
            index=models.Index(fields=["region"], name="cloud_insta_region_4d0cd8_idx"),
        ),
        migrations.AddIndex(
            model_name="cloudinstance",
            index=models.Index(fields=["status"], name="cloud_insta_status_332a94_idx"),
        ),
        migrations.AddIndex(
            model_name="cloudinstance",
            index=models.Index(fields=["owner"], name="cloud_insta_owner_b9a0e4_idx"),
        ),
        migrations.AddIndex(
            model_name="cloudinstance",
            index=models.Index(fields=["env"], name="cloud_insta_env_802200_idx"),
        ),
    ]
