# Generated by Django 4.2.28 on 2026-03-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cloudaccount",
            options={"verbose_name": "云账号", "verbose_name_plural": "云账号"},
        ),
        migrations.AlterModelOptions(
            name="clouddisk",
            options={"verbose_name": "云盘", "verbose_name_plural": "云盘"},
        ),
        migrations.AlterModelOptions(
            name="cloudinstance",
            options={"verbose_name": "云实例", "verbose_name_plural": "云实例"},
        ),
        migrations.AlterModelOptions(
            name="cloudnetwork",
            options={"verbose_name": "网络与安全", "verbose_name_plural": "网络与安全"},
        ),
        migrations.AlterModelOptions(
            name="cloudtag",
            options={"verbose_name": "实例标签", "verbose_name_plural": "实例标签"},
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="account_id",
            field=models.CharField(max_length=128, verbose_name="云账号ID"),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="auth_ref",
            field=models.CharField(max_length=255, verbose_name="凭证引用"),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="project_name",
            field=models.CharField(max_length=128, verbose_name="项目名称"),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="provider",
            field=models.CharField(max_length=32, verbose_name="云厂商"),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="status",
            field=models.CharField(
                default="active", max_length=32, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="disk_id",
            field=models.CharField(max_length=128, unique=True, verbose_name="云盘ID"),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="disk_type",
            field=models.CharField(max_length=64, verbose_name="云盘类型"),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="encrypted",
            field=models.BooleanField(default=False, verbose_name="是否加密"),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disks",
                to="assets.cloudinstance",
                verbose_name="挂载实例",
            ),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="size_gb",
            field=models.PositiveIntegerField(verbose_name="容量(GB)"),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="status",
            field=models.CharField(max_length=32, verbose_name="状态"),
        ),
        migrations.AlterField(
            model_name="clouddisk",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="assets.cloudaccount",
                verbose_name="所属账号",
            ),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="charge_type",
            field=models.CharField(
                choices=[("postpaid", "按量"), ("prepaid", "包年包月")],
                default="postpaid",
                max_length=32,
                verbose_name="计费方式",
            ),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="env",
            field=models.CharField(default="dev", max_length=16, verbose_name="环境"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="image_id",
            field=models.CharField(blank=True, max_length=128, verbose_name="镜像ID"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="instance_id",
            field=models.CharField(max_length=128, unique=True, verbose_name="实例ID"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="instance_type",
            field=models.CharField(max_length=64, verbose_name="实例规格"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="name",
            field=models.CharField(max_length=128, verbose_name="实例名称"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="os_type",
            field=models.CharField(blank=True, max_length=64, verbose_name="操作系统"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="owner",
            field=models.CharField(blank=True, max_length=64, verbose_name="负责人"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="private_ip",
            field=models.CharField(blank=True, max_length=64, verbose_name="私网IP"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="public_ip",
            field=models.CharField(blank=True, max_length=64, verbose_name="公网IP"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="region",
            field=models.CharField(max_length=64, verbose_name="地域"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="status",
            field=models.CharField(max_length=32, verbose_name="状态"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="cloudinstance",
            name="zone",
            field=models.CharField(blank=True, max_length=64, verbose_name="可用区"),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="cidr",
            field=models.CharField(max_length=64, verbose_name="网段"),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="inbound_rules",
            field=models.JSONField(default=list, verbose_name="入站规则"),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="networks",
                to="assets.cloudinstance",
                verbose_name="关联实例",
            ),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="outbound_rules",
            field=models.JSONField(default=list, verbose_name="出站规则"),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="security_group_id",
            field=models.CharField(max_length=128, verbose_name="安全组ID"),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="subnet_id",
            field=models.CharField(max_length=128, verbose_name="子网ID"),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="cloudnetwork",
            name="vpc_id",
            field=models.CharField(max_length=128, verbose_name="VPC ID"),
        ),
        migrations.AlterField(
            model_name="cloudtag",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="assets.cloudinstance",
                verbose_name="关联实例",
            ),
        ),
        migrations.AlterField(
            model_name="cloudtag",
            name="tag_key",
            field=models.CharField(max_length=64, verbose_name="标签键"),
        ),
        migrations.AlterField(
            model_name="cloudtag",
            name="tag_value",
            field=models.CharField(max_length=255, verbose_name="标签值"),
        ),
    ]
