# Generated by Django 4.2.28 on 2026-03-02 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SysGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sys_group",
            },
        ),
        migrations.CreateModel(
            name="SysUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=64)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("status", models.CharField(default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sys_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sys_user",
            },
        ),
        migrations.CreateModel(
            name="SysMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_name", models.CharField(max_length=64)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("catalog", "目录"),
                            ("menu", "菜单"),
                            ("button", "按钮"),
                        ],
                        max_length=16,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=255)),
                ("component", models.CharField(blank=True, max_length=255)),
                ("permission_code", models.CharField(max_length=128, unique=True)),
                ("sort", models.PositiveIntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
                ("status", models.CharField(default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="iam.sysmenu",
                    ),
                ),
            ],
            options={
                "db_table": "sys_menu",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="SysUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.sysgroup"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sys_user_group",
                "unique_together": {("user", "group")},
            },
        ),
        migrations.CreateModel(
            name="SysGroupMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.sysgroup"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.sysmenu"
                    ),
                ),
            ],
            options={
                "db_table": "sys_group_menu",
                "unique_together": {("group", "menu")},
            },
        ),
    ]
