# Generated by Django 4.2.28 on 2026-03-02 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sysgroup",
            options={"verbose_name": "用户组", "verbose_name_plural": "用户组"},
        ),
        migrations.AlterModelOptions(
            name="sysgroupmenu",
            options={
                "verbose_name": "用户组菜单权限",
                "verbose_name_plural": "用户组菜单权限",
            },
        ),
        migrations.AlterModelOptions(
            name="sysmenu",
            options={
                "ordering": ["sort", "id"],
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
            },
        ),
        migrations.AlterModelOptions(
            name="sysuser",
            options={"verbose_name": "用户资料", "verbose_name_plural": "用户资料"},
        ),
        migrations.AlterModelOptions(
            name="sysusergroup",
            options={"verbose_name": "用户组成员", "verbose_name_plural": "用户组成员"},
        ),
        migrations.AlterField(
            model_name="sysgroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sysgroup",
            name="description",
            field=models.CharField(blank=True, max_length=255, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="sysgroup",
            name="group_name",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="用户组名称"
            ),
        ),
        migrations.AlterField(
            model_name="sysgroup",
            name="status",
            field=models.CharField(
                default="active", max_length=16, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="sysgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="sysgroupmenu",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="iam.sysgroup",
                verbose_name="用户组",
            ),
        ),
        migrations.AlterField(
            model_name="sysgroupmenu",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="iam.sysmenu",
                verbose_name="菜单",
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="component",
            field=models.CharField(blank=True, max_length=255, verbose_name="前端组件"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="menu_name",
            field=models.CharField(max_length=64, verbose_name="菜单名称"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="menu_type",
            field=models.CharField(
                choices=[("catalog", "目录"), ("menu", "菜单"), ("button", "按钮")],
                max_length=16,
                verbose_name="菜单类型",
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="iam.sysmenu",
                verbose_name="父级菜单",
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="path",
            field=models.CharField(blank=True, max_length=255, verbose_name="路由路径"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="permission_code",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="权限编码"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="sort",
            field=models.PositiveIntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="status",
            field=models.CharField(
                default="active", max_length=16, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="是否可见"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="display_name",
            field=models.CharField(max_length=64, verbose_name="显示名称"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="手机号"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="status",
            field=models.CharField(
                default="active", max_length=16, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sys_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="系统用户",
            ),
        ),
        migrations.AlterField(
            model_name="sysusergroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="iam.sysgroup",
                verbose_name="用户组",
            ),
        ),
        migrations.AlterField(
            model_name="sysusergroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="系统用户",
            ),
        ),
    ]
