# Generated by Django 4.2.28 on 2026-03-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_id", models.CharField(max_length=128)),
                ("field", models.CharField(max_length=64)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("operator", models.CharField(max_length=64)),
                ("source", models.CharField(default="manual", max_length=32)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "change_log",
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="change_log_resourc_a01765_idx",
                    ),
                    models.Index(
                        fields=["operator"], name="change_log_operato_4440f1_idx"
                    ),
                    models.Index(
                        fields=["changed_at"], name="change_log_changed_ed8665_idx"
                    ),
                ],
            },
        ),
    ]
