# Generated by Django 4.2.28 on 2026-03-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelog",
            options={"verbose_name": "变更日志", "verbose_name_plural": "变更日志"},
        ),
        migrations.AlterField(
            model_name="changelog",
            name="changed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="field",
            field=models.CharField(max_length=64, verbose_name="变更字段"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="new_value",
            field=models.TextField(blank=True, verbose_name="新值"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="old_value",
            field=models.TextField(blank=True, verbose_name="旧值"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="operator",
            field=models.CharField(max_length=64, verbose_name="操作人"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="resource_id",
            field=models.CharField(max_length=128, verbose_name="资源ID"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="resource_type",
            field=models.CharField(max_length=64, verbose_name="资源类型"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="source",
            field=models.CharField(
                default="manual", max_length=32, verbose_name="来源"
            ),
        ),
    ]
